spring:
  application:
    name: rest-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest_with_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
      #ddl-auto: update
    properties:
      hibernate:
      #  dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
logging:
  level:
    #root: WARN #TRACE
    br.com.app: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true